import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "animate.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Just Group",
  description: "Generated by create next app",
  icons: "/logo.jpeg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="grid w-full backdrop-blur-lg h-[81px] fixed lg:h-[98px]">
          <nav className="nav top-0 fixed place-self-center w-10/12 mt-2 flex justify-between bg-white/20 backdrop-blur-md p-0 rounded-lg border border-gray-700 lg:p-2 animate__animated animate__bounceIn">
            <div className="ml-5 grid">
              <img src="/logo.jpeg" alt="" className="place-self-center w-[40px] h-[40px] rounded-md lg:w-[70px] lg:h-[70px]"/>
            </div>
            <div className="flex h-full align-middle">
              <Link className="p-6" href='#main'>
                Home
              </Link>
              <Link className="p-6" href='#member'>
                Members
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
